
---
- hosts: all
  gather_facts: true
  tasks:
    - name: Install all updates and reboot
      ansible.windows.win_updates:
        category_names: '*'
        reboot: yes
    
    # - name: Install all security, critical, and rollup updates
    #   ansible.windows.win_updates:
    #     category_names:
    #       - SecurityUpdates
    #       - CriticalUpdates
    #       - UpdateRollups

    # - name: Exclude updates based on the update title
    #   ansible.windows.win_updates:
    #     category_name:
    #     - SecurityUpdates
    #     - CriticalUpdates
    #     reject_list:
    #     - Windows Malicious Software Removal Tool for Windows
    #     - \d{4}-\d{2} Cumulative Update for Windows Server 2016    

    # - name: Search and download Windows updates without installing them
    #   ansible.windows.win_updates:
    #     state: downloaded    

    - name: Ensure we wait long enough for the updates to be applied during reboot
      ansible.windows.win_updates:
        reboot: yes
        reboot_timeout: 3600
